import type { Metadata } from "next";
import { Oswald, Playfair } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const geistMono = Playfair({
  variable: "--font-play-fair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jean Vinícius",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
